### ISSUE TITLE
How to use on nuxt 3

### ISSUE THREAD

**Issue by lyoko515** [jambonn/vue-next-progressbar#8]
How to use vue-next-progressbar in nuxt 3 thanks

**Comment by jambonn** [comment]
> How to use vue-next-progressbar in nuxt 3 thanks

I'm sorry for the slow answer, but I feel nuxt 3 is now in progress. You consult here: https://nuxtjs.org/docs/features/loading/#using

**Comment by lyoko515** [comment]
Thanks for your suggestion

**Comment by jambonn** [comment]
@lyoko515 Ok, if there is no problem, I will close the issue. Thank!
